name: ' 🧪 Test Windows'
on:
  push:
    branches:
      - test-1222
  workflow_dispatch:

jobs:
  test-os:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:

          - 20.x


        os: [windows-latest, macos-latest]

          # - macos-latest # Smoke test is enough for now.
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.2.0
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Check location of corepack before removing hostedtoolcache
        run: |
          which corepack
      - name: install Corepack
        run: |
          npm i -g --force corepack

      # - name: Prepend custom path to PATH
      #   run: |
      #     echo "C:\npm\prefix;${{ env.PATH }}" > $env:GITHUB_PATH
      - name: Check location of corepack before removing hostedtoolcache
        run: |
          which corepack
      - name: enable corepack
        run: |
          corepack enable
          corepack -v
          pnpm -v
        shell: bash
      - name: Install dependencies
        run: pnpm install
