name: ' 🧪 Test Windows'
on:
  push:
    branches:
      - test-1222
  workflow_dispatch:

jobs:
  test-os:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x
          - 23.x

        os:
          - windows-latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.2.0
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          check-latest: true
      # - name: Get exact Node.js version
      #   run: echo "NODE_VERSION=$(node -v)" >> $GITHUB_ENV
      #   shell: bash
      # - name: Clear hosted tool cache
      #   run: |
      #     $nodeVersion = $env:NODE_VERSION.TrimStart('v')
      #     Remove-Item -Force "C:\hostedtoolcache\windows\node\$nodeVersion\x64\corepack*"
      - name: Enable Corepack
        run: |
          npm i -g --force corepack
          corepack enable
          corepack -v
          pnpm -v
        shell: bash
      - name: Install dependencies
        run: pnpm install
