name: Test final

on:
  push:
    branches:
      - test-1244-eslint
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      # uses: fregante/setup-node@patch-1
      # uses: FloEdelmann/setup-node@patch-1
      # uses: priya-kinthali/setup-node@test-1244
      with:
        node-version: '22.14.0'
    - name: Test ESLint Compact Problem Matcher
      run: |
        echo "/home/runner/work/repo/file.ts: line 14, col 1, Error - 'webext-messenger' should be listed in the project's dependencies. Run 'npm i -S webext-messenger' to add it (import/no-extraneous-dependencies)"
        echo "   /home/runner/work/repo/file.ts: line 20, col 5, Warning - 'console' statements are not allowed (no-console)"
    - name: Install dependencies
      run: npm install

    