name: Test final

on:
  push:
    branches:
      - test-1244-eslint
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      # uses: fregante/setup-node@patch-1
      with:
        node-version: '22.14.0'
    - run: |
        echo "  /home/runner/work/repo/file.ts"
        echo "    14:1  error  'webext-messenger' should be listed in the project's dependencies. Run 'npm i -S webext-messenger' to add it  import/no-extraneous-dependencies"
        echo "    55:5  warning  Unexpected 'todo' comment: 'TODO: Add test for this eventuality:...'     no-warning-comments"

    