name: Reproduce Setup Error

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  reproduce-error:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # replace with your desired version

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      # Add other steps as needed