name: Reproduce Setup Error
on: [push]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - run: corepack enable
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        # registry-url: https://npm.pkg.github.com/priya-kinthali
        registry-url: https://npm.pkg.github.com
        scope: '@priya-kinthali'
        always-auth: true
      env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
    - name: Check env variable
      run: echo "Token set? ${NODE_AUTH_TOKEN:+yes}"
    - run: yarn workspaces focus --all --production
    - run: |
           yarn publish
           unset NPM_CONFIG_USERCONFIG 
      env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
    
      
 
      
