name: Reproduce Setup Error
on: [push]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - run: corepack enable
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'yarn'
    - name: Setup .yarnrc.yml
      run: |
          yarn config set npmScopes.my-org.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.my-org.npmAlwaysAuth true
          yarn config set npmScopes.my-org.npmAuthToken $NPM_AUTH_TOKEN
      env:
          NPM_AUTH_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
    - run: yarn workspaces focus --all --production
    - run: yarn npm publish 
      
    - name: Check env variable
      run: echo "Token set? ${NODE_AUTH_TOKEN:+yes}"
      
 
      
