name: Reproduce Setup Error
on: [push]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - run: corepack enable
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        # registry-url: https://npm.pkg.github.com/priya-kinthali
    
    - name: Install jq
      run: sudo apt-get install jq
      
    - name: Initialize Yarn package
      run: yarn init -y
      
    - name: Add scope to package name
      run: |
          jq '.name = "@${{ github.repository_owner }}/' + .name + '"' package.json > temp.json
          mv temp.json package.json
      
    - run: yarn workspaces focus --all --production
    - run: yarn npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.PUBLISH_GITHUB_TOKEN}}
