name: Reproduce Setup Error
on: [push]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - run: corepack enable
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - name: Install Yarn
      run: npm install -g yarn  
    - name: Initialize Yarn package
      run: yarn init -y 
    - run: yarn install --production
    - run: yarn publish
      env:
        NODE_AUTH_TOKEN: "${{secrets.PUBLISH_GITHUB_TOKEN}}"
    - name: Check env variable
      run: echo "Token set? ${NODE_AUTH_TOKEN:+yes}"
      
 
      
