# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: github Package

on:
  push:
    branches:
      - poc-956-yarnpatherror
jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: corepack enable
      - uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
          cache: 'yarn'
      
      - name: Install Dependencies
        run: npm install -g yarn
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
           path: path/to/directory
           key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      



 
