name: Test publish

on:
  push:
    branches:
      - test-686
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-latest, macos-13]
        #os: [ubuntu-latest]
        os: ['ubuntu-latest']

        # os: [self-hosted]
    runs-on: ${{ matrix.os }}
   
    steps:
    - uses: actions/checkout@v6
    # - uses: actions/setup-node@v6
    # - uses: Satishchoudhary94/setup-node@fix/oidc-support-1440
    #   with:
    #     node-version: '24.x'
    #     registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    # - run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    - uses: actions/setup-node@v6
      with:
        registry-url: 'https://npm.pkg.github.com'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  