name: Test corepack error-1222

on:
  # push:
  #   branches:
  #     - test-1222
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        node-version: ['20.18.2']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Verify corepack version
      run: corepack --version
    - name: Check location of corepack before removing hostedtoolcache
      run: which corepack
    - name: Install corepack
      run: npm i -g --force corepack && corepack enable
    - name: Check location of corepack before removing hostedtoolcache
      run: which corepack

    - name: Verify corepack version
      run: corepack --version


    # - name: Set up Node.js
    #   run: |
    #     Invoke-WebRequest -Uri https://nodejs.org/dist/v20.18.2/node-v20.18.2-x64.msi -OutFile node-v20.18.2-x64.msi
    #     Start-Process msiexec.exe -ArgumentList '/i', 'node-v20.18.2-x64.msi', '/quiet', '/norestart' -NoNewWindow -Wait
    #     node -v


  

