name: Test 1255

on:
  push:
    branches:
      - test-686
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-intel-15, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Set up Node.js 
      uses: susnux/setup-node@feat/support-dev-engines
      # uses: actions/setup-node@v6
      with:
        node-version-file: 'package.json'
        cache: 'npm'
    - name: Verify Latest Node.js Version
      run: node -v
    - name: Install dependencies  
      run: npm install