
name: Test corepack error-1222

on: [push, pull_request]

jobs:
  corepack-upgrade:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Check Windows version
    #   run: systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
    #   shell: cmd
    - name: Clear Node.js cache
      run: rmdir /S /Q C:\hostedtoolcache\windows\node
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.2'

    - name: Check Corepack version
      run: corepack -v
    - name: Enable Corepack
      run: npm install --global corepack@latest
    - name: Check Corepack version
      run: corepack -v
    - name: Enable pnpm
      run: corepack enable pnpm
    - name: Check pnpm version
      run: pnpm -v
      #test