name: ' 🧪 Test Windows'
on:
  push:
    branches:
      - test-1222
  workflow_dispatch:

jobs:
  test-os:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x
          - 23.x

        os:
          - windows-latest
          # - macos-latest # Smoke test is enough for now.
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.2.0
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Check location of corepack before removing hostedtoolcache
        run: |
          C:\Windows\System32\where.exe corepack
      - name: install Corepack
        run: |
              npm i -g --force corepack
      - name: Check location of corepack after installing corepack
        run: |
          C:\Windows\System32\where.exe corepack


      - name: Prepend custom path to PATH
        run: |
            #echo "C:\npm\prefix;${{ env.PATH }}" > $env:GITHUB_PATH
             echo "C:\npm\prefix\corepack;C:\npm\prefix\corepack.cmd;${{ env.PATH }}" > $env:GITHUB_PATH
        
      - name: Check location of corepack after installing corepack
        run: |
          C:\Windows\System32\where.exe corepack
      - name: enable corepack
        run: |
          corepack enable
          corepack -v
          pnpm -v
        shell: bash
      - name: Install dependencies
        run: pnpm install
