name: ' 🧪 Test Windows operation time'
on:
  # push:
  #   branches:
  #     - test-1244-eslint
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019, windows-latest, windows-2025]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        # cache: 'npm'
        # cache-dependency-path: '**/package-lock.json'
        cache: 'yarn'
        cache-dependency-path: "yarn.lock"
    - name: Install the packages
      run: yarn install --frozen-lockfile --ignore-engines
    # - run: npm ci
