name: Test cache

on:
  push:
    branches:
      - test-686
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-latest, macos-13]
        os: [self-hosted]
    runs-on: ${{ matrix.os }}
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    # - uses: pnpm/action-setup@v4
    #   with:
    #     version: 9
    - name: Setup Node.js
      uses: actions/setup-node@v4
      # uses: priya-kinthali/setup-node@sample-686
      with:
        node-version: '24'
        # cache: 'yarn'
        # cache-dependency-path: subdir/pnpm-lock.yaml
        enable-package-manager-cache: true
    # - run: npm ci
    # - name: Install dependencies
    #   run: npm install
    # - run: yarn install
    - run: pnpm install
  