# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: Node.js CI

on:
  push:
    branches: 
      - 1024-permission-issue-postcleanup
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        # node-version: [20.10.0]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node (prism)
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        node-version-file: '.tool-versions'
        
    - run: npm install
 



   

    
