name: Test final

on:
  push:
    branches:
      - test-1222
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.2'
        registry-url: 'https://registry.npmjs.org'

    - name: Install corepack globally
      run: npm install --global --force corepack@latest


    # - name: Enable corepack
    #   run: corepack enable

    - name: Verify Corepack version
      run: corepack --version
    - name: Install dependencies with pnpm
      run: pnpm install

