name: Test cache

on:
  push:
    branches:
      - test-686
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']

        # os: [self-hosted]
    runs-on: ${{ matrix.os }}
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
          fetch-depth: 0
    - name: Set up Node.js
      uses: actions/setup-node@5
      with:
          node-version: 24