
name: Test corepack error-1222

on: [push, pull_request]

jobs:
  corepack-upgrade:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Check Windows version
    #   run: systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
    #   shell: cmd
    - name: Clear Node.js cache
      run: Remove-Item -Recurse -Force C:\hostedtoolcache\windows\node
      shell: pwsh
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.2'

    - name: Check Corepack version
      run: corepack -v
    - name: Clear npm cache
      run: npm cache clean --force
    - name: Uninstall Corepack
      run: npm uninstall -g corepack
    # - name: Enable Corepack
      # run: npm install --global corepack@latest
      # run: npm i -g --force corepack@latest && corepack enable
      # run: npx corepack@latest enable
    - name: Download and install latest Corepack
      run: |
        curl -L https://github.com/nodejs/corepack/releases/latest/download/corepack.tgz -o corepack.tgz
        tar -xzf corepack.tgz
        mv package corepack
        cd corepack
        npm install -g .

    - name: Enable Corepack
      run: corepack enable
    - name: Check Corepack version
      run: corepack -v
    - name: Enable pnpm
      run: corepack enable pnpm
    - name: Check pnpm version
      run: pnpm -v
      #test