name: Test final

on:
  push:
    branches:
      - test-1244-eslint
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [macos-latest]

    runs-on: ${{ matrix.os }}
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.14.0'
    - name: Check npm version
      run: npm --version
    - name: Downgrade npm to version 10.6.0
      run: npm install -g npm@10.6.0
    - name: Check npm version
      run: npm --version
    - name: Trigger an npm install error
      run: npm run does-not-exist


    