name: Test final

on:
  push:
    branches:
      - test-1222
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.2'
    - name: Enable Corepack
      run: npm i -g --force corepack && corepack enable

    - name: Install dependencies
      run: pnpm install