name: Test corepack error-1222

on: [push, pull_request]

jobs:
  corepack-upgrade:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.2'

    - name: Install Latest Corepack
      run: npm i -g --force corepack@latest
    - name: Update PATH for Corepack
      run: echo "PATH=$env:APPDATA\\npm:$env:PATH" >> $env:GITHUB_ENV

    - name: Enable Corepack
      shell: pwsh
      run: corepack enable
        
    - name: Verify Corepack Version
      run: corepack --version