name: Test restore cache

on:
  push:
    branches:
      - test-686
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-latest, macos-13]
        #os: [ubuntu-latest]
        os: ['ubuntu-latest','macos-latest','windows-latest', 'ubuntu-24.04-arm', 'windows-11-arm', 'macos-15-intel']

        # os: [self-hosted]
    runs-on: ${{ matrix.os }}
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    # - uses: pnpm/action-setup@v6
    #   with:
    #     version: 10
    - name: Setup Node.js
      uses: actions/setup-node@v6
      # uses: priya-kinthali/setup-node@final-686
      # uses: priya-kinthali/setup-node@sample-686
      # uses: priya-kinthali/setup-node@package-manager-field-caching
      with:
        node-version: '24'
        # cache: 'npm'
        cache: 'yarn'
        # package-manager-cache: false
        # cache: 'pnpm'
        # cache-dependency-path: subdir/pnpm-lock.yaml
        # enable-package-manager-cache: true
    - name: Install latest Yarn
      run: npm install -g yarn@latest
    - name: Check Yarn version
      run: yarn --version
    # - run: npm ci
    # - name: Install dependencies
    #   run: npm install
    # - run: npm --version
    - run: yarn install
    # - run: pnpm install

    # - name: Normalize runner architecture
    #   shell: bash
    #   run: echo "ARCH=$(echo '${{ runner.arch }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    # - name: Output of cache path
    #   id: cachepath
    #   shell: bash
    #   # run: echo "path=$(npm config get cache)" >> $GITHUB_OUTPUT
    #   run: echo "path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
    #     # For yarn workflow, output of yarn cache dir (v1) or yarn config get cacheFolder (v2+)
    #   # run: echo "path=$(yarn cache dir)" >> $GITHUB_OUTPUT 
    # - name: Restore Node cache
    #   uses: actions/cache/restore@v5
    #   with:
    #     path: ${{ steps.cachepath.outputs.path }}
    #     # key: node-cache-${{ runner.os }}-${{ env.ARCH }}-npm-${{ hashFiles('**/package-lock.json') }}
    #     # key: node-cache-${{ runner.os }}-${{ env.ARCH }}-yarn-${{ hashFiles('**/yarn.lock') }}
    #     key: node-cache-${{ runner.os }}-${{ env.ARCH }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
    # # - run: npm ci
    # # - run: yarn install --frozen-lockfile
    # - run: pnpm install --frozen-lockfile
  