name: Test corepack error-1222

on:
  push:
    branches:
      - test-1222
  workflow_dispatch:

jobs:
  corepack-upgrade:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Set up Node.js
    #   run: |
    #     Invoke-WebRequest -Uri https://nodejs.org/dist/v20.18.2/node-v20.18.2-x64.msi -OutFile node-v20.18.2-x64.msi
    #     Start-Process msiexec.exe -ArgumentList '/i', 'node-v20.18.2-x64.msi', '/quiet', '/norestart' -NoNewWindow -Wait
    #     node -v
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
          node-version: 20.18.2
    - name: Clear npm cache
      run: npm cache clean --force

    - name: Clear Node.js and npm cache
      run: |
          rm -rf ~/.npm
          rm -rf ~/.node-gyp
          rm -rf ~/.cache

    - name: Uninstall existing Corepack
      run: npm uninstall --global corepack

    - name: Update npm to the latest version
      run: npm install -g npm@latest

    - name: Verify Node.js version
      run: node -v

    - name: Install Corepack
      run: npm install --global --force corepack@latest

    - name: Verify Corepack version
      run: corepack --version
  

