name: github Package

on:
  push:
    branches:
      - poc-956-yarnpatherror
jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with: 
          node-version: '20'
      
      
      - name: Install Dependencies
        run: corepack yarn install
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
           path: node_modules
           key: Ubuntu-build-${{ hashFiles('**/yarn.lock') }}
           restore-keys: |
              Ubuntu-build-